### ISSUE TITLE
Familiarize with Ray

### ISSUE THREAD

**Issue by rushirajnenuji** [QGreenland-Net/ray-exploration#1]

**Comment by trey-stafford** [comment]
Repo exploring the use of `ray`: https://github.com/QGreenland-Net/ray-exploration

Initial thoughts:

* Documentation is robust
* Multiple pathways for deployment / orchestration on kubernetes
* Feels "enterprise-y". Focus is on AI/ML, although Ray core can be used for a variety of more generic use-cases.
